### ISSUE TITLE
[Question]転送先に投げる際に、Ojのモードがobjectなのは意図的でしょうか?

### ISSUE THREAD

**Issue by tomboy67** [joker1007/octogate#9]
modeがobjectのままdumpをすると、最終的なjsonが
`"{\"^o\":\"Octogate::Target\",\"self\":{.......`のような形になってしまいます。

こちらは仕様でしょうか?なにか回避方法はありますでしょうか?

**Comment by joker1007** [comment]
これは意図的では無いですね。
テストコードを走らせてみた結果落ちるようになっています。
恐らくoj側で挙動が変更された部分があったのかも、と考えています。
ちょっと調査してみます。
報告ありがとうございました！ :bow:

**Comment by joker1007** [comment]
修正しました！

**Comment by tomboy67** [comment]
:+1:
